import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { articleSchema, breadcrumbSchema, faqPageSchema } from '@/app/structured-data/schemas'

export const dynamic = 'force-static'

const PUB_DATE = '2026-06-16'

export const metadata: Metadata = {
  title: 'GEO: AI Search Optimization Guide SA',
  description: 'Learn how GEO helps your site appear in Google AI Overviews, Perplexity & ChatGPT Search. Practical AI search optimization guide for South African businesses.',
  alternates: {
    canonical: 'https://www.nostalgic-studio.co.za/blog/what-is-generative-engine-optimization',
    languages: {
      'en-ZA': 'https://www.nostalgic-studio.co.za/blog/what-is-generative-engine-optimization',
      'x-default': 'https://www.nostalgic-studio.co.za/blog/what-is-generative-engine-optimization',
    },
  },
  openGraph: { title: 'What is Generative Engine Optimization (GEO)? | Nostalgic Studio', description: 'Optimize your website for AI-powered search engines like Google AI Overviews, Perplexity, and ChatGPT Search. A complete guide for South African businesses.', url: 'https://www.nostalgic-studio.co.za/blog/what-is-generative-engine-optimization', siteName: 'Nostalgic Studio', type: 'article', images: [{ url: 'https://www.nostalgic-studio.co.za/images/og-image.jpg', width: 1200, height: 630, alt: 'Generative Engine Optimization GEO Guide — Nostalgic Studio' }] },
}

const faqs = [
  { question: 'What is Generative Engine Optimization (GEO)?', answer: 'GEO is the practice of optimizing website content so AI-powered search engines (like Google AI Overviews, Perplexity, ChatGPT Search, and Claude) accurately cite and recommend your business in their generated answers.' },
  { question: 'How is GEO different from traditional SEO?', answer: 'Traditional SEO optimizes for search result links. GEO optimizes for AI-generated answers. While SEO focuses on keywords and backlinks, GEO emphasizes structured data, authoritative citations, clear formatting, and direct answers to questions.' },
  { question: 'Do I need GEO if I already do SEO?', answer: 'Yes. GEO complements SEO. Even if you rank #1 in traditional search, AI engines may not cite you unless your content is optimized for extraction. GEO ensures your business appears in AI-generated answers.' },
  { question: 'How do I optimize for GEO?', answer: 'Key tactics include implementing llms.txt files, adding structured data, creating authoritative FAQ sections, publishing original research, maintaining consistent NAP citations, and ensuring your content is easy for AI to parse and cite.' },
]

export default function GeoGuidePage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{
        __html: JSON.stringify([
          articleSchema({ url: '/blog/what-is-generative-engine-optimization', headline: 'What is Generative Engine Optimization (GEO)?', description: metadata.description ?? '', datePublished: PUB_DATE, articleSection: 'SEO' }),
          breadcrumbSchema([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'What is GEO?', url: '/blog/what-is-generative-engine-optimization' }]),
          faqPageSchema(faqs),
        ])
      }} />
      <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24">
        <p className="text-sm font-semibold text-primary tracking-wide uppercase mb-2">GEO — Generative Engine Optimization</p>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6">What is Generative Engine Optimization (GEO)?</h1>
        <p className="text-lg text-muted-foreground mb-8">A practical guide for South African businesses to appear in AI-generated search results</p>

        <div className="prose prose-lg max-w-none">
          <h2>The Shift from Search Links to AI Answers</h2>
          <p>Search is changing. Instead of a list of blue links, users now get instant answers generated by AI. Google AI Overviews, Perplexity, ChatGPT Search, and Claude are increasingly the first — and sometimes only — thing a user sees.</p>
          <p>If your business isn't optimized for these AI engines, you're invisible in the fastest-growing segment of search.</p>
          <p><strong>Generative Engine Optimization (GEO)</strong> is the practice of structuring your website so AI engines accurately cite, reference, and recommend your business in their generated responses.</p>

          <h2>Why GEO Matters for South African Businesses</h2>
          <p>South Africa has one of the highest mobile internet penetration rates in Africa, and AI-assisted search is growing rapidly. By early 2026, millions of South Africans use AI search daily — often bypassing traditional Google results entirely.</p>
          <p>For local businesses, this means a new battleground for visibility. GEO gives you a first-mover advantage in a space where most competitors haven't started optimizing.</p>

          <h2>GEO vs Traditional SEO: Key Differences</h2>
          <table className="w-full border-collapse border">
            <thead><tr><th className="border p-2 font-semibold">Aspect</th><th className="border p-2 font-semibold">Traditional SEO</th><th className="border p-2 font-semibold">Generative Engine Optimization</th></tr></thead>
            <tbody>
              <tr><td className="border p-2">Goal</td><td className="border p-2">Rank #1 in search results</td><td className="border p-2">Be cited in AI-generated answers</td></tr>
              <tr><td className="border p-2">Format</td><td className="border p-2">Links, titles, meta descriptions</td><td className="border p-2">Structured data, direct answers, citations</td></tr>
              <tr><td className="border p-2">Key Tactic</td><td className="border p-2">Backlinks + keywords</td><td className="border p-2">llms.txt + schema + authoritative content</td></tr>
              <tr><td className="border p-2">Target Audience</td><td className="border p-2">Human clickers</td><td className="border p-2">AI parsers + human readers</td></tr>
            </tbody>
          </table>

          <h2>How to Optimize for GEO in 2026</h2>
          <h3>1. Create an llms.txt File</h3>
          <p>An <code>llms.txt</code> file acts as a sitemap for AI engines. It tells crawlers like GPTBot, ClaudeBot, and PerplexityBot which pages are most important and how to navigate your site. Every South African business should have one at <code>yourdomain.com/llms.txt</code>.</p>

          <h3>2. Implement Comprehensive Structured Data</h3>
          <p>AI engines heavily rely on schema markup to understand your content. Implement LocalBusiness, Service, Product, FAQ, and Review schemas. Structured data is the single highest-impact GEO tactic — it directly feeds AI models with structured information about your business.</p>

          <h3>3. Authoritative, Well-Structured Content</h3>
          <p>AI engines prefer content that is clear, well-organized, and directly answers questions. Use heading hierarchies (H1 {'>'} H2 {'>'} H3), bullet points, tables, and short paragraphs. Include original data, statistics, and expert opinions — these are more likely to be cited.</p>

          <h3>4. Maintain Consistent NAP Citations</h3>
          <p>Name, Address, Phone number consistency across the web is critical. AI engines cross-reference your business information across multiple sources. Any inconsistency reduces trust and lowers the likelihood of citation.</p>

          <h3>5. Optimize for Question-Based Search</h3>
          <p>AI engines generate answers to specific questions. Create dedicated FAQ sections on your pages, write blog posts that answer common customer questions, and use the FAQ schema to mark them up.</p>

          <h2>Real Results: GEO in Action</h2>
          <p>Businesses that implement GEO are seeing 3-5x more visibility in AI-generated responses compared to those relying solely on traditional SEO. In South Africa, where AI adoption is accelerating rapidly, early adopters of GEO are capturing market share while competitors remain invisible in AI search.</p>

          <h2>Ready to Get Started?</h2>
          <p>GEO is not a replacement for SEO — it's an essential complement. We help South African businesses implement comprehensive GEO strategies including llms.txt files, structured data, and AI-optimized content.</p>
        </div>

        <div className="mt-12 p-6 bg-muted rounded-xl">
          <h3 className="text-xl font-bold mb-2">Frequently Asked Questions</h3>
          <div className="space-y-4 mt-6">
            {faqs.map((faq) => (
              <div key={faq.question}>
                <h4 className="font-semibold">{faq.question}</h4>
                <p className="text-muted-foreground mt-1">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-12 text-center">
          <Button asChild size="lg">
            <Link href="/contact">Get a Free GEO Audit <ArrowRight className="ml-2 h-4 w-4" /></Link>
          </Button>
        </div>
      </article>
    </>
  )
}
